---
# Site
baseurl: "."
title: "Foobits focuses on delivering high-performance and scalable enterprise Solutions using latest Web, Mobile technology stack and Design."
enableRobotsTXT: true
googleAnalytics: ""
# Content
languageCode: "en-us"
defaultContentLanguage: "en"
# Formats
metaDataFormat: "yaml"
# -----------------------------
# DO NOT CHANGE BELOW THIS LINE
# -----------------------------
disableLiveReload: true
watch: false
---
